### ISSUE TITLE
Kreirati strukturu projekta

### ISSUE THREAD

**Issue by n-ratinac** [iLiciLi/kviz#1]
Napraviti nove direktorijume /frontend i /backend.

Backend je po uzoru na flask tutorijal
Frontend je koriscenjem komande 

```shell
npm create skeleton-app@latest frontend
```
i da se isprati do kraja postupak
Potrebno je da:

- svaki deo projekta (backend i frontend) sadrzi vlastiti .gitignore fajl
- u frontend-u treba svaka tema da bude omogucena

Na kraju bi trebalo da je moguce pokrenuti i frontend i backend aplikacije na zasebnim portovima.

**Comment by iLiciLi** [comment]
Napravljeni su /frontend i /backend direktorijumi.
Za svaki je ponaosob dodat .gitignore i mogu se pokrenuti na različitim portovima.
Unutar frontend-a su takođe dodati bitni fajlovi za Skeleton UI.
**[COMMITOVI](https://github.com/iLiciLi/kviz/commits/master/?since=2024-04-15&until=2024-04-16)**
