### ISSUE TITLE
{FRONTEND} Obaveštavanje korisnika

### ISSUE THREAD

**Issue by iLiciLi** [iLiciLi/kviz#10]
Napraviti Svelte komponente unutar **frontend/lib direktorijuma** koje imaju ulogu da obaveštavaju korisnika o odgovorima sa servera **(ako unese pogrešno email, password, ako je registrovan, ako je ulogovan)**.

Ove komponente trebaju da budu **div-ovi (mali prozorčići) koji će imati export promenljivu tekst unutar koje će biti response servera**.

Ovi prozorčići će se pojavljivati kada User, nakon pritisnutog dugmeta Login/Register, dobije response od servera.

**Comment by n-ratinac** [comment]
Ne mora da se pravi nova komponenta, može da se koristi Toast komponenta iz SkeletonUI-a.
