### ISSUE TITLE
{FRONTEND} Login i Register komponente

### ISSUE THREAD

**Issue by iLiciLi** [iLiciLi/kviz#4]
Potrebno je napraviti 2 Svelte komponente : **Login** i **Register**.
Frontend.

**Comment by iLiciLi** [comment]
Ovaj **Issue** je rešen !
[Ognjenov commit](https://github.com/iLiciLi/kviz/commit/fc0cae7a98ab57e512cae384727651a610dddcb0)

**Comment by n-ratinac** [comment]
Ubuduce, prvo napraviti branch za issue, zaduziti clana tima i dozvoliti mu da komituje na branch.
