### ISSUE TITLE
{BACKEND} Baza podataka

### ISSUE THREAD

**Issue by iLiciLi** [iLiciLi/kviz#6]
Dodati SQL bazu podataka sa tabelama za **user-e** i za **pitanja**!
Takođe dodati u glavnoj Flask skripti da se baza inicijalizuje prilikom pokretanja.

**Comment by iLiciLi** [comment]
Ovaj **Issue** je rešen.
[Sarin commit](https://github.com/iLiciLi/kviz/commit/3834a0bcc0b694a519748b5682b6568e8b468fb3)

**Comment by n-ratinac** [comment]
Ubuduce, kreirati zasebne brancheve za svaki issue.

![image](https://github.com/iLiciLi/kviz/assets/149359865/9c6cabbc-456f-4d08-b952-2e685320b70a)
